### PR TITLE
Add update(key, updater, cb)

### PR DESCRIPTION
**Pull request by Havvy**
This allows a person to get and set a key in one expression.

It's a convenience function.

### CODE REVIEW

**Comment by felixge** [comment]
Not sure this is needed. This whole library is meant to be minimal, so convenience functions don't seem to be a good fit?

**Comment by Havvy** [comment]
The alternative would be to make a dirty-extensions library, but that seems like pointless library proliferation. Or to write this function everywhere we want to use it, but then calling it looks different (function call vs. method call)

Are you looking for minimalism, or are you just looking to minimize the number of moving parts.

If it's the latter, this doesn't add any new moving parts.

**Comment by felixge** [comment]
I don't use this library, or node for that matter, anymore. So I'm happy to let those who actually use it decide the direction. You seem to be one of them. If you're interested, I'd be happy to add you as a committer to the repo and npm, then you can make changes as you see fit.

**Comment by Havvy** [comment]
Sure, that would also let me go through the backlog of issues on the tracker, plus one other not on the tracker issue.

**Comment by felixge** [comment]
Added u on Github. What's your npm user name?

**Comment by Havvy** [comment]
"havvy"

**Pull request merged**
